### ISSUE TITLE
如何操作可以使得扫描完成后 不上报到sonarqube

### ISSUE THREAD

**Issue by dnlixiaoxin** [lowkeyfish/sonar-intellij-plugin#15]
RT

**Comment by lowkeyfish** [comment]
开发插件时就希望不上报到 SonarQube，不过暂时没有找到方法。目前插件的实现原理是在 SonarScanner 扫描后上报前做了拦截，在这个时机阻塞了上报动作，然后解析了报告，在上报后这些本地报告会被 SonarScanner 自动删除。SonarScanner 现在默认的行为是不在本地保留报告，一定要上报到 SonarQube 的。
