### ISSUE TITLE
Unable to set project name/key or branch name

### ISSUE THREAD

**Issue by benze** [lowkeyfish/sonar-intellij-plugin#4]
I ran across your plugin and thought it might be interesting to try out, but unfortunately, you do not allow the user to override the sonar.*** properties as part of the project settings.  I am not sure why that is the case, but it prevents me from setting my Sonar project name and/or branch.

It would be nice to be able to provide that information as part of the configuration:
sonar.projectKey
sonar.branch.name

Thanks,

Eric

**Comment by lowkeyfish** [comment]
Your proposal is very good, I will release a version as soon as possible to support more properties.

**Comment by lowkeyfish** [comment]
@benze version v0.1.7 already supports more property settings.
