### ISSUE TITLE
能否支持findbugs和checkstyle

### ISSUE THREAD

**Issue by YorkHwang** [lowkeyfish/sonar-intellij-plugin#7]
你好，插件写得非常好！！支持
我测试是没法支持checkstyle和findbugs规则的，跟官方的sonarlint插件相比优势在哪里？
期望：支持sonar上findbugs和checkstyle等其他类型的规则

**Comment by lowkeyfish** [comment]
当前插件的检查结果可以理解为和 sonar-maven-plugin 插件一致，SonarQube 中质量配置中是可以混合多种规则的（FindBugs，Checkstyle，PMD 等），因此正常的情况下插件的检查结果是包含所有你在 SonarQube 上配置的规则的，我自己实际使用中 SonarQube 上也是多种检查工具的规则集合。

和 SonarLint 对比的话，SonarLint 仅可以显示 Sonar 自己的规则，不支持 SonarQube 上已配置的第三方检测工具的规则，但 SonarLint 可以在 IDE 中实现实时分析。当前插件因为底层基于 SonarScanner 所以可以和 SonarQube 服务端结果保持一致，但是同样是因为基于 SonarScanner 的原因无法做到实时分析，因为再小的代码检测范围对于 SonarScanner 来说耗时也是秒级。

当前插件对应的使用场景一般是让使用者在 IDE 中可以实现和服务器端一致的检测结果，同时修复问题时不用在 IDE 和 SonarQube 网页间频繁切换，将代码检测提示都集成到 IDE 中。
