### ISSUE TITLE
支持属性列表

### ISSUE THREAD

**Issue by bestv5** [lowkeyfish/sonar-intellij-plugin#8]
能不能列出一个支持的属性列表，方便在properties中配置

**Comment by lowkeyfish** [comment]
支持的配置项和 [SonarScanner](https://docs.sonarqube.org/latest/analysis/analysis-parameters/) 一致，但基于插件的交互方式所以默认忽略了[这些属性](https://github.com/lowkeyfish/sonar-intellij-plugin/blob/main/README.zh-CN.md#sonarscanner%E5%B1%9E%E6%80%A7)。插件开发过程中并未测试过所有的 SonarScanner 配置属性，如果使用中遇到了问题也希望提出来以便改进插件。
